on:
  push:
    branches: main

jobs:
  compile-rankings:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::jsonlite
            any::tidyverse
            any::rvest

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: |
        Rscript -e 'source("compile-womens.R")'
        Rscript -e 'source("compile-mens.R")'

      - name: Commit results
        run: |
          git config --local user.email actions@github.com
          git config --local user.name actions-user
          git add data/womens-rankings.rds
          gir add data/mens-rankings.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions